### PR TITLE
UPD: ShowFileProperties: show Creation time on MacOS

### PR DESCRIPTION
**Pull request by rich2014**
dialog `Show File Properties`: `Creation time` shown on MacOS

### CODE REVIEW

**Comment by rich2014** [comment]
image

**Comment by JonnyTech** [comment]
Can this be implemented on Linux?

Currently, from my `ext4` partition, `stat` displays file creation date (aka Birth):

```
$ stat doublecmd
  File: doublecmd
  Size: 16348728  	Blocks: 31936      IO Block: 4096   regular file
Device: 803h/2051d	Inode: 1051513     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-04-06 12:31:03.000000000 +0400
Modify: 2023-04-02 15:29:51.000000000 +0400
Change: 2023-04-06 12:31:04.067892350 +0400
 Birth: 2023-04-06 12:31:03.711897385 +0400
```

But DC does not:

image

**Comment by alexx2000** [comment]
Yes. DC supports creation time under Linux, you can add "Creation time" column to file panel or tooltip, at this time. Technically I can add it to file properties dialog too.

**Comment by JonnyTech** [comment]
> Technically I can add it to file properties dialog too.

Yes, please. Thank you.

**Comment by alexx2000** [comment]
New labels should be invisible by default.

**Comment by rich2014** [comment]
> New labels should be invisible by default.

fixed.

**Pull request merged**
