### PR TITLE
UPD: F7-mkdir: improve the layout (label example overlay buttons occasionally)

### PR DESCRIPTION
**Pull request by rich2014**
UPD: F7-mkdir: improve the layout, add space between controls.
and avoid label example overlay buttons when "Extended syntax" checked.

### CODE REVIEW

**Comment by rich2014** [comment]
image

**Comment by rich2014** [comment]
image

**Comment by rich2014** [comment]
@alexx2000 could you please check it?

**Comment by alexx2000** [comment]
In this case window change height on checkbox on/off. So far I don't know how to do it better.

**Comment by rich2014** [comment]
how about this version? by aligning the OK button to the bottom of the form, and setting the form's
MinHeight, keep the height of the form unchanged

**Comment by alexx2000** [comment]
No, it works incorrect. Controls can be much bigger and window autosize does not work in this case.
So I think it's better to use first variant but clear `lblExample.Caption` (in `RefreshExample`) by space symbol instead empty string.

**Comment by rich2014** [comment]
set space instead of empty string, it works fine.
check it please @alexx2000 

> ... But clear `lblExample.Caption` (in `RefreshExample`) by space symbol instead empty string or ...

**Comment by alexx2000** [comment]
Also need to add `RefreshExample` here:
```
    RefreshExample;
    cbMkDir.SelectAll;
    Result := (ShowModal = mrOK);
```

**Pull request merged**
