### PR TITLE
Corrections on the French translation

### PR DESCRIPTION
**Pull request by Arkanoid1973**
Hi,

Some corrections on the French translation proposed to merge into the active branch 1.1x

Thanks

### CODE REVIEW

**Comment by Skif-off** [comment]
You forgot about [fuzzy](https://github.com/doublecmd/doublecmd/wiki/Translation#user-content-About_fuzzy_entries_fuzzy_translation).

**Comment by Arkanoid1973** [comment]
Hi,
Yes it's right.
It's done now.
Thanks
Have a nice day

**Comment by Skif-off** [comment]
Sorry for the curiosity, why not the master branch too? :)

**Comment by Arkanoid1973** [comment]
Hi,
I updated the master branch a week ago in another ticket.
That being said, I am waiting for the next active version to check in the application that there are no more translation imperfections... 
At that time, I will update the 2 active and master branches with a version translation which, I hope, will be almost perfect :)
Have a nice day

**Pull request merged**
