### PR TITLE
ADD: DARWIN: add a WlxPlugin MacPreview

### PR DESCRIPTION
**Pull request by rich2014**
add a WlxPlugin MacPreview:
1. implemented using MacOS Native QuickLook Preview
2. handle all files except those without extension
3. tested on MacOS 12

### CODE REVIEW

**Comment by rich2014** [comment]
image

**Comment by rich2014** [comment]
image

**Comment by rich2014** [comment]
image

**Comment by rich2014** [comment]
image

**Comment by rich2014** [comment]
image

**Comment by Skif-off** [comment]
`plugins/wlx/MacPreview/src/MacPreview.lpr`, 4th line:
```
   Explorer preview plugin
```
Should it be something like "MacPreview plugin"?

**Comment by rich2014** [comment]
> `plugins/wlx/MacPreview/src/MacPreview.lpr`, 4th line:
> 
> ```
>    Explorer preview plugin
> ```
> 
> Should it be something like "MacPreview plugin"?

THX. it's fixed.

**Pull request merged**
