### PR TITLE
UPD: hold ALT key while dragdropping, popup ask menu

### PR DESCRIPTION
**Pull request by rich2014**
UPD: hold ALT key while dragdropping, popup ask menu (Copy/Move/Create Link/...), especially useful on Macs (due to lack of right mouse button)

### CODE REVIEW

**Comment by rich2014** [comment]
@alexx2000 

could you please check it?

**Comment by alexx2000** [comment]
ALT key already used to force activation of external darg&drop. So I don't sure that it will not conflict. It is needed to check under all platforms.

**Comment by rich2014** [comment]
1. it's just for drop destination, not the source, i guess there should be no conflicts
2.or should it be modified to be LCL_COCOA only?

**Comment by alexx2000** [comment]
I will check how it work with other widgetsets.

**Comment by ags1234** [comment]
Using doublecmd-1.1.0.r10306.i386-win32 on Windows 11.
Nothing different happens if I press Alt while dragging a file. It just calls for the Copy window, like not pressing Alt.
The only difference is the mouse tool tip. Without Alt is a big green plus sign, with Alt is a little grey plus.

**Comment by rich2014** [comment]
could you please check with other widgetset? @alexx2000 

> I will check how it work with other widgetsets.

**Comment by alexx2000** [comment]
Checked.

**Pull request merged**
