### PR TITLE
Update on Greek Translation for the latest Trunk

### PR DESCRIPTION
**Pull request by anastasioskazakis**
[doublecmd.el.po.zip](https://github.com/doublecmd/doublecmd/files/7774844/doublecmd.el.po.zip)

### CODE REVIEW

**Comment by alexx2000** [comment]
Attached archive contains file based on some old version. Pull request are wrong too.

**Comment by anastasioskazakis** [comment]
Hello,

Sorry I used the old link as source:
https://sourceforge.net/p/doublecmd/code/HEAD/tree/trunk/language/doublecmd.el.po?format=raw

What and where should I use? Could you pls send me the link?

If pull request is wrong, does this means I have to make an issue to the
GitHub?

Tassos

Στις Παρ 24 Δεκ 2021 στις 10:36 μ.μ., ο/η Alexander Koblov <
***@***.***> έγραψε:

**Comment by j2969719** [comment]
here is a github raw link if you dont want to pull the whole source tree 
https://github.com/doublecmd/doublecmd/raw/master/language/doublecmd.el.po

**Comment by alexx2000** [comment]
> If pull request is wrong, does this means I have to make an issue to the GitHub?

I don't know, but it should include only one file.

**Pull request closed without merging**
