### PR TITLE
fix build on macOS

### PR DESCRIPTION
**Pull request by deep-soft**
- Install Lazarus 
  uses: gcarreno/setup-lazarus@v3.2.15

- temporary fix source code 
  Install gnu-sed
  not found CocoaConst, CocoaMenus, replace with CocoaWSMenus
  not found NSSTR_DARK_NAME and NSAppearanceNameDarkAqua, replace with NSAppearanceNameAqua

### CODE REVIEW

**Comment by rich2014** [comment]
I found this in `build-mac`:

```
(3104) Compiling fpdbglinuxextra.pas
/Users/runner/work/doublecmd/doublecmd/components/fpdebug/fpdbglinuxextra.pas(11,3)
 Fatal: (10022) Can't find unit SysCall used by FpDbgLinuxExtra
Fatal: (1018) Compilation aborted
make[2]: *** [fpdebug.ppu] Error 1
make[1]: *** [lazbuildlclpackages] Error 2
make: *** [lazbuild] Error 2
Error: Process completed with exit code 2.
```

**Comment by alexx2000** [comment]
@rich2014, Lazarus build under macOS  was broken by this [commit](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/1633420b5533eae952556d2c26b2fb958801ba6a).

**Comment by deep-soft** [comment]
@alexx2000 : from build-mac.yml
```
 /usr/bin/sudo installer -package /Volumes/fpcsrc-3.2.2/fpcsrc-3.2.2-20210709.pkg -target /
  installer: Package name is Free Pascal Sources
  installer: Installing at base path /
  installer: The install was successful.
  _downloadLazarus - Downloading https://sourceforge.net/projects/lazarus/files/Lazarus%20macOS%20x86-64/Lazarus%202.2.6/fpc-3.2.2.intelarm64-macosx.dmg
  _downloadLazarus - Using cache restored into /Users/runner/work/_temp/installers/fpc.dmg
  /usr/bin/sudo hdiutil attach /Users/runner/work/_temp/installers/fpc.dmg

```
so:
fpc 3.2.2
lazarus 2.2.6

Didn't know about Lazarus 2.2.6, those are the stable versions installed by 
`gcarreno/setup-lazarus@v3.2.15`
This was the only way I succesfully build for macOS

**Comment by deep-soft** [comment]
So, I should delete this PR...

**Comment by rich2014** [comment]
fixed in Lazarus by [b5db1bf52fb3c4b7c2dd4fa38b123d425a449b58](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commits/main?ref_type=heads)

**Comment by deep-soft** [comment]
##### succesfully build with
alexx2000/setup-fpc
lazarus-version: "stable"

In the meantime I was trying to add 3.0RC2 option to src/Lazarus.ts (fork of alexx2000/setup-fpc) but failed.
Changes to src/Lazarus.ts was not applied when I use the action.
I think I miss something, some step needed to update the github action ...

**Comment by alexx2000** [comment]
> alexx2000/setup-fpc
> lazarus-version: "stable"

Really it is a Lazarus 3.99 alpha.

> Changes to src/Lazarus.ts was not applied when I use the action.
> I think I miss something, some step needed to update the github action ...

`src/Lazarus.ts` is a TypeScript source code. It should be compiled into `dist/main/index.js`. I don't know how.

**Pull request closed without merging**
