### PR TITLE
ADD: Built-in editor menu item "Edit - Time/Date".

### PR DESCRIPTION
**Pull request by R0bur**
The implemented feature inserts current time and date into the current position of the edited text, like it Notepad in Windows does.

### CODE REVIEW

**Comment by Skif-off** [comment]
Is a hard coded template a good solution?

**Comment by R0bur** [comment]
The 'ddddd' template will be replaced with a short date representation as it is set in the system locale settings. It should be exactly the same as in the Notepad implemented. But I tested it in Windows 10 only.

**Comment by Skif-off** [comment]
Yes, I know how these characters will work. It has always seemed to me that using `yyyy.mm.dd hh:mm` or `yyyy.mm.dd hh:mm:ss` is more practical.

> It should be exactly the same as in the Notepad implemented.

I am not ready to consider this program authoritative :)
For example, Geany allows to [set a template](https://www.geany.org/manual/current/index.html#template-preferences) (for the "Insert date" command too). Or maybe without GUI like [DateTimeFormat](https://doublecmd.github.io/doc/en/configxml.html#DateTimeFormat).

Maybe it makes sense to rename "Time/Date" to "Insert date"?

P.S. In any case, I'm ready to wait for Lua support in the editor :)

**Comment by R0bur** [comment]
> 
> > It should be exactly the same as in the Notepad implemented.
> 
> I am not ready to consider this program authoritative :) For example, Geany allows to [set a template](https://www.geany.org/manual/current/index.html#template-preferences) (for the "Insert date" command too). Or maybe without GUI like [DateTimeFormat](https://doublecmd.github.io/doc/en/configxml.html#DateTimeFormat).

[AkelPad](https://akelpad.sourceforge.net/) uses the same simple implementation as Notepad.

> Maybe it makes sense to rename "Time/Date" to "Insert date"?

All details are easier to fix when the basic feature will be implemented.

**Comment by j2969719** [comment]
imo this is the most common use case and customizable template imo overengineering because even if you suddenly need another form, it is much faster to edit the date in the editor than to dig into the settings and study the docs on templates

and for more flexibility or some highly specialized use cases, perhaps lua may help in the future

**Comment by Skif-off** [comment]
@R0bur

> AkelPad uses the same simple implementation as Notepad.

If you ask me "_Skif-off, who do you love more, hmm... Monica Bellucci or AkelPad?_", I'll be a little confused :))
But, in any case, see `DateInsertFormat` in `AkelFiles/Docs/AkelHelp-Eng.htm`.

@j2969719

> imo this is the most common use case and customizable template imo overengineering

You're probably right, I don't know.

**Pull request merged**
