### PR TITLE
add dependabot

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for the app. I add [Dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide). I hope it is useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by Skif-off** [comment]
Excuse my curiosity :), how can this service be useful in this case?

**Comment by alexx2000** [comment]
Hi, I guess Dependabot nothing knows about FreePascal/Lazarus. So I think it is useless in our case.

**Comment by theavege** [comment]
You use github-action. I add dependabot for github-action.

**Comment by alexx2000** [comment]
OK.

**Pull request merged**
