### PR TITLE
Some additional functions for Lua

### PR DESCRIPTION
**Pull request by Skif-off**
DC.ExpandVar, DC.GetPluginField, DC.GoToFile, DC.ExpandEnv;
SysUtils.FileSetTime, SysUtils.GetFileProperty, SysUtils.RemoveDirectory.

### CODE REVIEW

**Comment by alexx2000** [comment]
`TFileSystemFileSource.CreateFileFromFile` should be in the `try..except`, it genarates exception when file not found.

**Comment by Skif-off** [comment]
Thanks! Please take a look now: I tried to fix it and also changed the algorithm of these two functions a bit.

**Comment by alexx2000** [comment]
Algorithm is better now. But I don't see a fix. It should be like:
```
try
  AFile := TFileSystemFileSource.CreateFileFromFile(lua_tostring(L, 1));
except
  lua_pushnil(L);
  Exit;
end;
```

**Comment by Skif-off** [comment]
It seems to be fixed now.

Perhaps this
```pascal
   if AIndex > 9 then
    begin
      lua_pushnil(L);
      Exit;
    end;
    try
      ...
```
should be replaced with something like
```pascal
    if AIndex < 10 then
    begin
      try
        ...
```

**Comment by Skif-off** [comment]
Done.

P.S. I also thought about getting the total number of items and the number of selected ones, but I'm not sure.

**Pull request merged**
