### PR TITLE
UPD: use -sfx switch for cli rar

### PR DESCRIPTION
**Pull request by j2969719**

### CODE REVIEW

**Comment by Skif-off** [comment]
`*.run` is usually text file, isn't it?

**Comment by j2969719** [comment]
¿
when sfx checkbox is enabled, dc sets the archive extension to `exe` on windows and to `run` on other platforms.
btw rar for linux with this switch for some reason creates archive with the extension `sfx`, regardless of the specified extension

**Comment by Skif-off** [comment]
It was a question for "general development" :)

P.S. Yes, I know about `GetSfxExt`, but I've never tried packing with this plugin, so I didn't know about the `sfx` extension in some (all?) cases.

**Comment by j2969719** [comment]
ithink its just rar's quirk, 7z doesnt have this issue

**Comment by alexx2000** [comment]
Why only console RAR? WinRAR supports this option too.

**Comment by j2969719** [comment]
iirc when testing on wine, winrar created sfx even without this switch. so i thought that the absence of this switch was intended since winrar is used there by default

**Pull request merged**
