### PR TITLE
UPD: ExtractDlg: improve the layout

### PR DESCRIPTION
**Pull request by rich2014**
upd #628 
tested on MacOS 12 and Windows 11

### CODE REVIEW

**Comment by rich2014** [comment]
image

**Comment by Skif-off** [comment]
Strange background, last field size
example
Lazarus: 2.2.4.0 / FPC: 3.2.2, Win7x32

**Comment by Skif-off** [comment]
Lazarus from "main" / FPC 3.2.2: better

example2

Well, @alexx2000 can repalce `Пароль (для зашифрованных файлов):` on `Пароль для зашифрованных:`...

**Comment by alexx2000** [comment]
I applied modified version of the patch. It fixes labels background color and password label width.

**Comment by rich2014** [comment]
it works well on MacOS 12

**Pull request closed without merging**
